### ISSUE TITLE
Нэйминг

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/lesson-19-js#1]
https://github.com/AnnLuschik/lesson-19-js/blob/6deeae79a0176d46540fe9e7ec8a4663ca298d8f/script.js#L20

Я думаю можно придумать более подходящее имя, слишком размытое, у тебя эе эта функция для молальных окон стил  накладывает, так и укажи это. А то такое чувство, что она затемняет что угодно)

**Comment by AnnLuschik** [comment]
Готово.
