### ISSUE TITLE
Валидация

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/lesson-19-js#2]
https://github.com/AnnLuschik/lesson-19-js/blob/6deeae79a0176d46540fe9e7ec8a4663ca298d8f/script.js#L60

Смотри, я бы предложил тебе создавать нового юзера, только в том случае, если форма валидна, логично же, что юзера надо добавить в список, только после того как все верно заполнено. Поэтому, сделай к примеру объект-валидационный, который ты после нажатия кнопки регистрации, проверишь на отсутствие пустых полей и только если все ок, ты создашь юзера через конструктор и пойдешь дальше. Кстате не понимаю зачем тебе тут цикл while еще, можно же просто сделать функцию проверки, которая к примеру возвращает true/false в зависимости от заполненности объекта. Воркфлоу такой - 
Юзер жмет кнопку регистрации => формируется объект-валидации => передаем в функцию, которая ищет пустые поля => если их нет, возвращается true => создаем пользователя и выводим сообщение об успешной регистрации, а то оно у тебя сейчас отсутствует.

**Comment by AnnLuschik** [comment]
Выполнено.
